export const DEFAULT_RAIL_SIZE = "240px"
export const DEFAULT_DRAWER_SIZE = "300px"
export const DEFAULT_BREAKPOINT = 768
export const POINTER_PROXIMITY_THRESHOLD = 48
export const SCROLL_TOWARD_THRESHOLD = 4
